// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// trailcount
IntegerVector trailcount(NumericVector& x);
RcppExport SEXP _PAIT_trailcount(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(trailcount(x));
    return rcpp_result_gen;
END_RCPP
}
// orderC
IntegerVector orderC(NumericVector& x);
RcppExport SEXP _PAIT_orderC(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(orderC(x));
    return rcpp_result_gen;
END_RCPP
}
// trailCount_QxRx_ordered_abs_Y
IntegerVector trailCount_QxRx_ordered_abs_Y(LogicalVector& Qx_TF_ordered, NumericVector& ordered_abs_Y, IntegerVector& trailcount_ordered_abs_Y);
RcppExport SEXP _PAIT_trailCount_QxRx_ordered_abs_Y(SEXP Qx_TF_orderedSEXP, SEXP ordered_abs_YSEXP, SEXP trailcount_ordered_abs_YSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< LogicalVector& >::type Qx_TF_ordered(Qx_TF_orderedSEXP);
    Rcpp::traits::input_parameter< NumericVector& >::type ordered_abs_Y(ordered_abs_YSEXP);
    Rcpp::traits::input_parameter< IntegerVector& >::type trailcount_ordered_abs_Y(trailcount_ordered_abs_YSEXP);
    rcpp_result_gen = Rcpp::wrap(trailCount_QxRx_ordered_abs_Y(Qx_TF_ordered, ordered_abs_Y, trailcount_ordered_abs_Y));
    return rcpp_result_gen;
END_RCPP
}
// phi
double phi(double a, double b, double c, double d);
RcppExport SEXP _PAIT_phi(SEXP aSEXP, SEXP bSEXP, SEXP cSEXP, SEXP dSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    Rcpp::traits::input_parameter< double >::type c(cSEXP);
    Rcpp::traits::input_parameter< double >::type d(dSEXP);
    rcpp_result_gen = Rcpp::wrap(phi(a, b, c, d));
    return rcpp_result_gen;
END_RCPP
}
// Tk_phiC
NumericVector Tk_phiC(NumericVector& x, NumericVector& y, int n, NumericMatrix& DMatX);
RcppExport SEXP _PAIT_Tk_phiC(SEXP xSEXP, SEXP ySEXP, SEXP nSEXP, SEXP DMatXSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector& >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< NumericMatrix& >::type DMatX(DMatXSEXP);
    rcpp_result_gen = Rcpp::wrap(Tk_phiC(x, y, n, DMatX));
    return rcpp_result_gen;
END_RCPP
}
// T_phiC
double T_phiC(NumericVector x, NumericVector y, int ITR);
RcppExport SEXP _PAIT_T_phiC(SEXP xSEXP, SEXP ySEXP, SEXP ITRSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type ITR(ITRSEXP);
    rcpp_result_gen = Rcpp::wrap(T_phiC(x, y, ITR));
    return rcpp_result_gen;
END_RCPP
}
// corC
double corC(NumericVector x, NumericVector y);
RcppExport SEXP _PAIT_corC(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(corC(x, y));
    return rcpp_result_gen;
END_RCPP
}
// Tk_corC
NumericVector Tk_corC(NumericVector& x, NumericVector& y, int n, NumericMatrix& DMatX);
RcppExport SEXP _PAIT_Tk_corC(SEXP xSEXP, SEXP ySEXP, SEXP nSEXP, SEXP DMatXSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector& >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< NumericMatrix& >::type DMatX(DMatXSEXP);
    rcpp_result_gen = Rcpp::wrap(Tk_corC(x, y, n, DMatX));
    return rcpp_result_gen;
END_RCPP
}
// T_corC
double T_corC(NumericVector x, NumericVector y, int ITR);
RcppExport SEXP _PAIT_T_corC(SEXP xSEXP, SEXP ySEXP, SEXP ITRSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type ITR(ITRSEXP);
    rcpp_result_gen = Rcpp::wrap(T_corC(x, y, ITR));
    return rcpp_result_gen;
END_RCPP
}
// Tk_dcorC
NumericVector Tk_dcorC(NumericVector& x, NumericVector& y, int n, NumericMatrix& DMatX);
RcppExport SEXP _PAIT_Tk_dcorC(SEXP xSEXP, SEXP ySEXP, SEXP nSEXP, SEXP DMatXSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector& >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< NumericMatrix& >::type DMatX(DMatXSEXP);
    rcpp_result_gen = Rcpp::wrap(Tk_dcorC(x, y, n, DMatX));
    return rcpp_result_gen;
END_RCPP
}
// T_dcorC
double T_dcorC(NumericVector x, NumericVector y, int ITR);
RcppExport SEXP _PAIT_T_dcorC(SEXP xSEXP, SEXP ySEXP, SEXP ITRSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type ITR(ITRSEXP);
    rcpp_result_gen = Rcpp::wrap(T_dcorC(x, y, ITR));
    return rcpp_result_gen;
END_RCPP
}
// Tk_phi
NumericVector Tk_phi(NumericVector x, NumericVector y);
RcppExport SEXP _PAIT_Tk_phi(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(Tk_phi(x, y));
    return rcpp_result_gen;
END_RCPP
}
// Tk_cor
NumericVector Tk_cor(NumericVector x, NumericVector y);
RcppExport SEXP _PAIT_Tk_cor(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(Tk_cor(x, y));
    return rcpp_result_gen;
END_RCPP
}
// Tk_dcor
NumericVector Tk_dcor(NumericVector x, NumericVector y);
RcppExport SEXP _PAIT_Tk_dcor(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(Tk_dcor(x, y));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_PAIT_trailcount", (DL_FUNC) &_PAIT_trailcount, 1},
    {"_PAIT_orderC", (DL_FUNC) &_PAIT_orderC, 1},
    {"_PAIT_trailCount_QxRx_ordered_abs_Y", (DL_FUNC) &_PAIT_trailCount_QxRx_ordered_abs_Y, 3},
    {"_PAIT_phi", (DL_FUNC) &_PAIT_phi, 4},
    {"_PAIT_Tk_phiC", (DL_FUNC) &_PAIT_Tk_phiC, 4},
    {"_PAIT_T_phiC", (DL_FUNC) &_PAIT_T_phiC, 3},
    {"_PAIT_corC", (DL_FUNC) &_PAIT_corC, 2},
    {"_PAIT_Tk_corC", (DL_FUNC) &_PAIT_Tk_corC, 4},
    {"_PAIT_T_corC", (DL_FUNC) &_PAIT_T_corC, 3},
    {"_PAIT_Tk_dcorC", (DL_FUNC) &_PAIT_Tk_dcorC, 4},
    {"_PAIT_T_dcorC", (DL_FUNC) &_PAIT_T_dcorC, 3},
    {"_PAIT_Tk_phi", (DL_FUNC) &_PAIT_Tk_phi, 2},
    {"_PAIT_Tk_cor", (DL_FUNC) &_PAIT_Tk_cor, 2},
    {"_PAIT_Tk_dcor", (DL_FUNC) &_PAIT_Tk_dcor, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_PAIT(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
