# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

trailcount <- function(x) {
    .Call(`_PAIT_trailcount`, x)
}

orderC <- function(x) {
    .Call(`_PAIT_orderC`, x)
}

trailCount_QxRx_ordered_abs_Y <- function(Qx_TF_ordered, ordered_abs_Y, trailcount_ordered_abs_Y) {
    .Call(`_PAIT_trailCount_QxRx_ordered_abs_Y`, Qx_TF_ordered, ordered_abs_Y, trailcount_ordered_abs_Y)
}

phi <- function(a, b, c, d) {
    .Call(`_PAIT_phi`, a, b, c, d)
}

Tk_phiC <- function(x, y, n, DMatX) {
    .Call(`_PAIT_Tk_phiC`, x, y, n, DMatX)
}

T_phiC <- function(x, y, ITR) {
    .Call(`_PAIT_T_phiC`, x, y, ITR)
}

corC <- function(x, y) {
    .Call(`_PAIT_corC`, x, y)
}

Tk_corC <- function(x, y, n, DMatX) {
    .Call(`_PAIT_Tk_corC`, x, y, n, DMatX)
}

T_corC <- function(x, y, ITR) {
    .Call(`_PAIT_T_corC`, x, y, ITR)
}

Tk_dcorC <- function(x, y, n, DMatX) {
    .Call(`_PAIT_Tk_dcorC`, x, y, n, DMatX)
}

T_dcorC <- function(x, y, ITR) {
    .Call(`_PAIT_T_dcorC`, x, y, ITR)
}

Tk_phi <- function(x, y) {
    .Call(`_PAIT_Tk_phi`, x, y)
}

Tk_cor <- function(x, y) {
    .Call(`_PAIT_Tk_cor`, x, y)
}

Tk_dcor <- function(x, y) {
    .Call(`_PAIT_Tk_dcor`, x, y)
}

